"""Discord API module for MCP server."""

from .discord import (
    AddRoleArgs,
    CreateChannelArgs,
    GetServerInfoArgs,
    GetUserInfoArgs,
    ListMembersArgs,
    ModerateMessageArgs,
    ReadMessagesArgs,
    RemoveRoleArgs,
    SendMessageArgs,
    add_role,
    cleanup_discord_client,
    create_channel,
    get_server_info,
    get_user_info,
    init_discord_client,
    list_members,
    moderate_message,
    read_messages,
    remove_role,
    send_message,
)

__all__ = [
    "init_discord_client",
    "cleanup_discord_client",
    "send_message",
    "read_messages",
    "get_user_info",
    "moderate_message",
    "get_server_info",
    "list_members",
    "add_role",
    "remove_role",
    "create_channel",
    "SendMessageArgs",
    "ReadMessagesArgs",
    "GetUserInfoArgs",
    "ModerateMessageArgs",
    "GetServerInfoArgs",
    "ListMembersArgs",
    "AddRoleArgs",
    "RemoveRoleArgs",
    "CreateChannelArgs",
]
